#!/usr/bin/env python3
"""Generated output blocks in markdown: regenerate or verify.

Conventions rule: no figure appears in prose unless it is produced by a
committed fixture and regenerated by `make verify`. The mechanism is a
marked fenced block whose content IS the output of a committed command:

    <!-- generated-block: uv run python code/python/main.py code/fixtures/runs.jsonl -->
    ```json
    ...command stdout, verbatim...
    ```
    <!-- /generated-block -->

Commands run with the repository root as the working directory, via
`bash -c`. `--check` (the default, wired into `make verify`) fails when any
block differs from its command's current output; `--write` regenerates the
blocks in place.
"""

from __future__ import annotations

import argparse
import re
import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
SKIP_DIRS = {"node_modules", "_reference", ".git", ".venv", "__pycache__", "dist"}
SKIP_FILES = {"RESEARCH.md", "PROPOSAL.md", "BUILD_PROGRESS.md"}
EXEMPT_DIRS = {"fixtures", "expected"}

BLOCK_RE = re.compile(
    r"<!-- generated-block: (?P<command>[^\n]+?) -->\n"
    r"```(?P<lang>[^\n]*)\n"
    r"(?P<content>.*?)"
    r"```\n"
    r"<!-- /generated-block -->",
    re.DOTALL,
)


def markdown_files(root: Path) -> list[Path]:
    files = []
    for path in root.rglob("*.md"):
        if any(part in SKIP_DIRS or part in EXEMPT_DIRS for part in path.parts):
            continue
        if path.name in SKIP_FILES and path.parent == root:
            continue
        files.append(path)
    return sorted(files)


def _rel(path: Path) -> str:
    return str(path.relative_to(REPO_ROOT)) if path.is_relative_to(REPO_ROOT) else str(path.name)


def run_command(command: str) -> str:
    proc = subprocess.run(
        ["bash", "-c", command],
        cwd=REPO_ROOT,
        capture_output=True,
        text=True,
        timeout=300,
    )
    if proc.returncode != 0:
        raise RuntimeError(
            f"generated-block command failed (exit {proc.returncode}): {command}\n"
            f"stderr: {proc.stderr.strip()[:400]}"
        )
    return proc.stdout.rstrip("\n") + "\n"


def process_file(path: Path, write: bool) -> list[str]:
    text = path.read_text(encoding="utf-8")
    errors: list[str] = []
    changed = False

    def replace(match: re.Match) -> str:
        nonlocal changed
        command = match.group("command").strip()
        current = match.group("content")
        try:
            fresh = run_command(command)
        except RuntimeError as error:
            errors.append(f"{_rel(path)}: {error}")
            return match.group(0)
        if fresh != current:
            if write:
                changed = True
                return (
                    f"<!-- generated-block: {command} -->\n"
                    f"```{match.group('lang')}\n{fresh}```\n<!-- /generated-block -->"
                )
            got_first = next(
                (
                    f"line {i + 1}: {b!r} != {f!r}"
                    for i, (b, f) in enumerate(
                        zip(current.split("\n"), fresh.split("\n"), strict=False)
                    )
                    if b != f
                ),
                f"length {len(current.splitlines())} vs {len(fresh.splitlines())} lines",
            )
            errors.append(
                f"{_rel(path)}: generated block drifted from "
                f"`{command}` (first divergence: {got_first}); run "
                f"`uv run python tools/gen_readme_blocks.py --write`"
            )
        return match.group(0)

    new_text = BLOCK_RE.sub(replace, text)
    if write and changed:
        path.write_text(new_text, encoding="utf-8")
    return errors


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--write", action="store_true", help="regenerate blocks in place")
    parser.add_argument(
        "--check", action="store_true",
        help="verify blocks match their commands' output (the default mode)",
    )
    args = parser.parse_args()
    if args.write and args.check:
        parser.error("--write and --check are mutually exclusive")

    blocks = 0
    errors: list[str] = []
    for path in markdown_files(REPO_ROOT):
        text = path.read_text(encoding="utf-8")
        found = len(BLOCK_RE.findall(text))
        if found == 0:
            continue
        blocks += found
        errors.extend(process_file(path, args.write))

    mode = "write" if args.write else "check"
    print(f"gen-readme-blocks[{mode}]: {blocks} generated block(s) processed")
    for error in errors:
        print(f"  FAIL {error}")
    if errors:
        print(f"gen-readme-blocks: {len(errors)} error(s)")
        return 1
    print("gen-readme-blocks: OK")
    return 0


if __name__ == "__main__":
    sys.exit(main())
